#### Target Specific Settings ####

# Needed for display and LVGL (prevent stack overflow and crash)
CONFIG_MAIN_STACK_SIZE=8192
# Enable Zephyr system workqueue for k_work_delayable
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
# CONFIG_SYSTEM_WORKQUEUE_PRIORITY=2

# Use with ESP32 chip revision 1
CONFIG_ESP32_USE_UNSUPPORTED_REVISION=y

#### Display Specific Settings ####

# Enable display driver (ST7735R)
CONFIG_DISPLAY=y

# Configure LVGL
CONFIG_LVGL=y
#CONFIG_LV_MEM_CUSTOM=y
CONFIG_LV_Z_BITS_PER_PIXEL=16
CONFIG_LV_COLOR_16_SWAP=y
CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_LV_TXT_ENC_UTF8=y

# Enable LVGL widgets
CONFIG_LV_CONF_MINIMAL=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_BUTTON=y
CONFIG_LV_LABEL_TEXT_SELECTION=y
CONFIG_LV_LABEL_LONG_TXT_HINT=y
CONFIG_LV_USE_LINE=y

# Config touchscreen
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_INPUT=y

CONFIG_MIPI_DBI=y
CONFIG_MIPI_DBI_SPI=y
CONFIG_ESP32_SPIM=y
CONFIG_DISPLAY=y
CONFIG_SENSOR=y

# Input drivers
CONFIG_INPUT_XPT2046=y

CONFIG_LV_Z_MEM_POOL_SYS_HEAP=y

CONFIG_LV_USE_THEME_DEFAULT=y
CONFIG_LV_THEME_DEFAULT_GROW=y
CONFIG_LV_THEME_DEFAULT_TRANSITION_TIME=80
CONFIG_LV_USE_FLEX=y
CONFIG_LV_USE_GRID=y
CONFIG_LV_USE_TFT_ESPI=y
CONFIG_LV_USE_ILI9341=y

#### Logging Specific Settings ####

# Enable logging
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_RUNTIME_FILTERING=y
CONFIG_LOG_BUFFER_SIZE=2048
CONFIG_LOG_PRINTK=y
CONFIG_LOG_PROCESS_TRIGGER_THRESHOLD=0
CONFIG_COVERAGE=n
CONFIG_LOG_TAG_MAX_LEN=15

#### Network Specific Settings ####

# Enable Wifi
CONFIG_WIFI=y
CONFIG_INIT_STACKS=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_HOSTNAME_ENABLE=y
CONFIG_NET_HOSTNAME_DYNAMIC=y

CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
#CONFIG_NET_IPV6=y
CONFIG_NET_UDP=y
#CONFIG_NET_TCP=y
#CONFIG_DNS_RESOLVER=y
#CONFIG_DNS_RESOLVER_AI_MAX_ENTRIES=10

CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_SERVICE=y
#CONFIG_HTTP_CLIENT=y

# Use DHCP for IPv4
CONFIG_NET_DHCPV4=y

# Or assign a static IP address (useful for testing)
# Following line must be enabled, otherwise WiFi connection fails with -1.
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_INIT_TIMEOUT=1

# SNTP
CONFIG_SNTP=y

#### Filesystem Specific Settings ####

# Filesystem
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y

#### Self-defined Specific Settings ####

#  parameters
CONFIG_CYD_ENABLE_TOUCH=y

# Custom Project configuration
CONFIG_PROJECT_NAME="Cyd-Zephyr"

CONFIG_DEPLOY_EMBEDDED=y


# End of prj.conf